import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Separator } from "@/components/shadcn/separator"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Pokémon Explorer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased h-full`}>

        {children}

        <Separator />
        <footer className="row-start-3 flex gap-[24px] flex-wrap items-center justify-center h-1/5 mt-10 mb-10">
            <b>Thank you for using Pokémon Browser!</b>
        </footer>

      </body>
    </html>
  );
}
